postgres:
  host: localhost
  port: 5432
  user: phamthanh
  password: password
  dbname: chat_app
redis:
  addr: localhost:6379
jwt:
  secret: secret-key
services:
  user:
    grpc_addr: "localhost:50051"
    http_addr: ":8080"
  message:
    grpc_addr: "localhost:50052"
    http_addr: ":8081"